app/__init__.py
import toml
from flask import Flask

import _thread

def load_config():
    with open('config.toml') as config_file:
        config = toml.loads(config_file.read())
    return config

config = load_config()
def create_app(configs):
    app = Flask(__name__)
    app.config.update(**configs)

    # Blueprints
    from app.blueprints.main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from app.blueprints.changes import changes as changes_blueprint
    app.register_blueprint(changes_blueprint, url_prefix='/changes')

    from app.blueprints.resources import resources as resources_blueprint
    app.register_blueprint(resources_blueprint, url_prefix='/resources')

    from app.blueprints.pulls import pulls as pulls_blueprint
    app.register_blueprint(pulls_blueprint, url_prefix='/pulls')

    from app.blueprints.auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix='/auth')

    from app.libs.projects import _calcutor_commitsize, _git_update, _ostree_update
    _thread.start_new_thread(_calcutor_commitsize, ())
    _thread.start_new_thread(_git_update, ())
    _thread.start_new_thread(_ostree_update, ())

    return app

app/blueprints/changes/__init__.py
from flask import Blueprint

changes = Blueprint('changes', __name__)

from . import views

app/blueprints/changes/views.py
from flask import abort, render_template
from . import changes
import git
from app import config

@changes.route('/', methods=['GET'])
def index():
    package = config['flask'].get('package_dir')
    try:
        project = git.Repo(package)
    except git.exc.InvalidGitRepositoryError:
        return abort(404)
    return render_template('changes/index.html', project=project)

app/blueprints/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

app/blueprints/main/views.py
from flask import render_template
from flask import Response
from . import main
from app.libs.projects import get_flatdebs
from app import config
import os
from flask import abort, redirect
import subprocess

@main.route('/', methods=['GET'])
def index():
    flatdebs = get_flatdebs()
    return render_template('main/index.html', flatdebs=flatdebs)

@main.route('/install/<pkgname>', methods=['GET'])
def install(pkgname):
    result = '<pre style="overflow: hidden !important;">'
    result += "flatpak --user remote-add --no-gpg-verify flatdeb %s" % config['flask'].get('repo_url')
    result += "</br>"
    result += "flatpak --user install flatdeb %s" % pkgname
    result += "</pre>"
    return result

@main.route('/appstream/<pkgname>.flatpakref', methods=['GET'])
def appstream(pkgname):
    result = '''[Flatpak Ref]
Name=%s
Branch=master
Title=%s from flatdeb
Url=http://10.0.10.32/repo
IsRuntime=false
''' % (pkgname, pkgname)
    return Response(result, mimetype="application/vnd.flatpak.ref")

@main.route('/<pkgname>', methods=['GET'])
def get(pkgname):
    flatdebs = get_flatdebs()
    flatdeb = flatdebs.get(pkgname)
    if not flatdeb:
        return abort(404)

    flatdeb.repo_url = config['flask'].get('repo_url')
    ostreedir = config['flask'].get('ostree_dir')
    app_ostree = os.path.join(ostreedir, 'refs/heads/app', pkgname, 'x86_64')
    for branch in os.listdir(app_ostree):
        if os.path.exists(os.path.join(app_ostree, branch)):
            _, output = subprocess.getstatusoutput(" ".join(['ostree', '--repo=%s' % ostreedir, 'show', 'app/%s/x86_64/%s' % (pkgname, branch)]))
            flatdeb.ostree = output
            break

    project_dir = config['flask'].get('package_dir')
    pkgname = pkgname.split('.')[-1]
    if os.path.exists(os.path.join(project_dir, pkgname + ".yaml")):
        with open(os.path.join(project_dir, pkgname + ".yaml")) as fp:
            flatdeb.yaml = fp.read()
    else:
        flatdeb.yaml = os.path.join(project_dir, pkgname + ".yaml")
    return render_template('flatdebs/get.html', flatdeb=flatdeb)

app/blueprints/pulls/__init__.py
from flask import Blueprint

pulls = Blueprint('pulls', __name__)

from . import views

app/blueprints/pulls/views.py
from flask import abort, render_template, request
from . import pulls
import git
from app import config
from app.libs.projects import cache, logger

@pulls.route('/', methods=['GET', 'POST'])
def index():
    if request.method == 'POST':
        username = request.form.get('username', None)
        origin = request.form.get('origin', None)
        ref = request.form.get('ref', None)
        if username is None or origin is None or ref is None:
            logger.error('add ostree pull - %s' % str(request.form))
            abort(503)

        cache.add_pull(username, origin, ref)
        logger.info('add ostree pull - %s %s %s' % (username, origin, ref))
        return 'add successful'

    elif request.method == 'GET':
        pulls = cache.execute('SELECT * FROM pulls ORDER BY -id')
        return render_template('pulls/index.html', pulls=pulls)

app/blueprints/resources/__init__.py
from flask import Blueprint

resources = Blueprint('resources', __name__)

from . import views

app/blueprints/resources/views.py
from . import resources
from app import config
import os
from flask import request, abort
from flask import send_file, jsonify
from app.libs.projects import get_commitsize

@resources.route('/icons/<pkgname>', methods=['GET'])
def get_icon(pkgname, fallback='application-x-executable.svg'):
    pkgname = pkgname.split('.')[-1]
    icons = config['flask'].get('icons_dir')
    has_icon = False
    for ext in ['svg', 'svgz', 'png']:
        icon_file = os.path.join(icons, pkgname + '.' + ext)
        if os.path.exists(icon_file):
            has_icon = True
            break

    if has_icon is False:
        icon_file = os.path.join(icons, fallback)
        if not os.path.exists(icon_file):
            abort(404)

    return send_file(icon_file)

@resources.route('/cache', methods=['GET'])
def get_cache_commit(fallback=0):
    ref = request.args.get('ref', None)
    commitsize = 'Unknown'
    if ref.startswith('/'):
        ref = ref[1:]
    if ref is not None:
        commitsize = get_commitsize('app/' + ref, calculate=False)
    return jsonify({'commitsize': commitsize})

@resources.route('/commit', methods=['GET'])
def commit_calculate(fallback=0):
    ref = request.args.get('ref', None)
    if ref.startswith('/'):
        ref = ref[1:]
    if ref is not None:
        commitsize = get_commitsize('app/' + ref, calculate=True)
    return jsonify({'commitsize': commitsize})

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}FlatDeb{% endblock %}

{% block styles %}
<link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet">
{% endblock %}

{% block head %}
{{ super() }}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon">
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles.css') }}">
{% endblock %}


{% block navbar %}
<style>
    .navbar-brand {
        padding: 2px;
    }
</style>
<div class="navbar navbar" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url_for('main.index') }}"><img alt="Flatdeb" height=45px src="/static/logo.png"/></a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{{ url_for('main.index') }}">Home</a></li>
                <li><a href="{{ url_for('changes.index') }}">Changes</a></li>
                <li><a href="{{ url_for('pulls.index') }}">Pulls</a></li>
            </ul>
        </div>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="container">
    {% for message in get_flashed_messages() %}
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
    {% endfor %}

    {% block page_content %}{% endblock %}
</div>
{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/jquery.min.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
{% endblock %}

app/templates/bootstrap/base.html
{% block doc -%}
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
  <head>
    {%- block head %}
    <title>{% block title %}{{title|default}}{% endblock title %}</title>

    {%- block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {%- endblock metas %}

    {%- block styles %}
    <!-- Bootstrap -->
    <link href="{{bootstrap_find_resource('css/bootstrap.css', cdn='bootstrap')}}" rel="stylesheet">
    {%- endblock styles %}
    {%- endblock head %}
  </head>
  <body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}
    {% block navbar %}
    {%- endblock navbar %}
    {% block content -%}
    {%- endblock content %}

    {% block scripts %}
    <script src="{{bootstrap_find_resource('jquery.js', cdn='jquery')}}"></script>
    <script src="{{bootstrap_find_resource('js/bootstrap.js', cdn='bootstrap')}}"></script>
    {%- endblock scripts %}
    {%- endblock body %}
  </body>
{%- endblock html %}
</html>
{% endblock doc -%}

app/templates/bootstrap/fixes.html
{% macro ie8() %}
    <!--[if lt IE 9]>
          <script src="{{bootstrap_find_resource('html5shiv.js', cdn='html5shiv', local=False)}}"></script>
          <script src="{{bootstrap_find_resource('respond.js', cdn='respond.js', local=False)}}"></script>
    <![endif]-->
{% endmacro %}

app/templates/bootstrap/google.html
{% macro analytics(account) -%}
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', '{{account}}']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
{% endmacro %}

{% macro uanalytics(id, options='auto', domain=None) %}
{# The uanalytics macro currently contains a hack to support legacy code.
   The old signature was ``uanalytics(id, domain)`` when domain was a required
   parameter that was passed on to the ga() function.

   To preserve old behavior, if options is not a dictionary, it is passed on
   unchanged. The ``domain`` parameter is added to not break calls with named
   parameters, it will override any other value for options.

   More modern code can simply pass any desired option to the analytics
   function as desired.
#}
{%- if domain != None %}
{%- set options = domain %}
{%- endif %}
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', {{id|tojson|safe}}, {{options|tojson|safe}});
  ga('send', 'pageview');
</script>
{% endmacro %}

app/templates/bootstrap/pagination.html
{% macro _arg_url_for(endpoint, base) %}
{# calls url_for() with a given endpoint and **base as the parameters,
   additionally passing on all keyword_arguments (may overwrite existing ones)
 #}
{%- with kargs = base.copy(),
         _ = kargs.update(kwargs) -%}
{{url_for(endpoint, **kargs)}}
{%- endwith %}
{%- endmacro %}

{% macro render_pagination(pagination,
                           endpoint=None,
                           prev=('&laquo;')|safe,
                           next=('&raquo;')|safe,
                           size=None,
                           ellipses='…',
                           args={}
                           )
-%}
{# poor man's "do": #}
{% with url_args = {},
        _ = url_args.update(request.view_args if not endpoint else {}),
        __ = url_args.update(request.args if not endpoint else {}),
        ___ = url_args.update(args) %}
{% with endpoint = endpoint or request.endpoint %}
<nav>
  <ul class="pagination{% if size %} pagination-{{size}}{% endif %}"{{kwargs|xmlattr}}>
  {# prev and next are only show if a symbol has been passed. #}
  {% if prev != None -%}
    <li{% if not pagination.has_prev %} class="disabled"{% endif %}><a href="{{_arg_url_for(endpoint, url_args, page=pagination.prev_num) if pagination.has_prev else '#'}}">{{prev}}</a></li>
  {%- endif -%}

  {%- for page in pagination.iter_pages() %}
    {% if page %}
      {% if page != pagination.page %}
        <li><a href="{{_arg_url_for(endpoint, url_args, page=page)}}">{{page}}</a></li>
      {% else %}
        <li class="active"><a href="#">{{page}} <span class="sr-only">(current)</span></a></li>
      {% endif %}
    {% elif ellipses != None %}
      <li class="disabled"><a href="#">{{ellipses}}</a></li>
    {% endif %}
  {%- endfor %}

  {% if next != None -%}
    <li{% if not pagination.has_next %} class="disabled"{% endif %}><a href="{{_arg_url_for(endpoint, url_args, page=pagination.next_num) if pagination.has_next else '#'}}">{{next}}</a></li>
  {%- endif -%}
  </ul>
</nav>
{% endwith %}
{% endwith %}
{% endmacro %}

app/templates/bootstrap/utils.html
{% macro flashed_messages(messages=None, container=True, transform={
  'critical': 'danger',
  'error': 'danger',
  'info': 'info',
  'warning': 'warning',
  'debug': 'info',
  'notset': 'info',
  'message': 'info',
}, default_category=None, dismissible=False) -%}
{% with messages = messages or get_flashed_messages(with_categories=True) -%}
{% if messages -%} {# don't output anything if there are no messages #}

{% if container -%}
<!-- begin message block -->
<div class="container flashed-messages">
  <div class="row">
    <div class="col-md-12">
{% endif -%}

{% for cat, msg in messages %}      <div class="alert alert-{{transform.get(cat.lower(), default_category or cat)}}{% if dismissible %} alert-dismissible{% endif %}" role="alert">
{% if dismissible %}        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>{% endif %}
        {{msg}}
      </div>
{%- endfor -%}

{% if container %}
    </div>
  </div>
</div>
<!-- end message block -->
{% endif -%}

{% endif -%}
{% endwith -%}
{% endmacro -%}


{% macro icon(type=None, extra_classes=[]) -%}
<span{{ ({'class': (['glyphicon', 'glyphicon-' + type] + extra_classes)|join(' ')})|xmlattr}}{{kwargs|xmlattr}}></span>
{%- endmacro %}


{% macro form_button(url, content, method='post', class='btn-link') -%}
<form style="display: inline;" action='{{url}}' method='{{method}}'><button class="{{class|safe}}">{{content}}</button></form>
{%- endmacro %}

app/templates/bootstrap/wtf.html
{% macro form_errors(form, hiddens=True) %}
  {%- if form.errors %}
    {%- for fieldname, errors in form.errors.items() %}
      {%- if bootstrap_is_hidden_field(form[fieldname]) and hiddens or
             not bootstrap_is_hidden_field(form[fieldname]) and hiddens != 'only' %}
        {%- for error in errors %}
          <p class="error">{{error}}</p>
        {%- endfor %}
      {%- endif %}
    {%- endfor %}
  {%- endif %}
{%- endmacro %}

{% macro _hz_form_wrap(horizontal_columns, form_type, add_group=False, required=False) %}
{% if form_type == "horizontal" %}
  {% if add_group %}<div class="form-group{% if required %} required{% endif %}">{% endif %}
  <div class="col-{{horizontal_columns[0]}}-offset-{{horizontal_columns[1]}}
              col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}
             ">
{% endif %}
{{caller()}}

{% if form_type == "horizontal" %}
  {% if add_group %}</div>{% endif %}
  </div>
{% endif %}
{% endmacro %}

{% macro form_field(field,
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    button_map={}) %}

{# this is a workaround hack for the more straightforward-code of just passing required=required parameter. older versions of wtforms do not have
the necessary fix for required=False attributes, but will also not set the required flag in the first place. we skirt the issue using the code below #}
{% if field.flags.required and not required in kwargs %}
{% set kwargs = dict(required=True, **kwargs) %}
{% endif %}

{% if field.widget.input_type == 'checkbox' %}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    <div class="checkbox">
      <label>
        {{field()|safe}} {{field.label.text|safe}}
      </label>
    </div>
  {% endcall %}
{%- elif field.type == 'RadioField' -%}
  {# note: A cleaner solution would be rendering depending on the widget,
     this is just a hack for now, until I can think of something better #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    {% for item in field -%}
      <div class="radio">
        <label>
          {{item|safe}} {{item.label.text|safe}}
        </label>
      </div>
    {% endfor %}
  {% endcall %}
{%- elif field.type == 'SubmitField' -%}
  {# deal with jinja scoping issues? #}
  {% set field_kwargs = kwargs %}

  {# note: same issue as above - should check widget, not field type #}
  {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
    {{field(class='btn btn-%s' % button_map.get(field.name, 'default'),
            **field_kwargs)}}
  {% endcall %}
{%- elif field.type == 'FormField' -%}
{# note: FormFields are tricky to get right and complex setups requiring
   these are probably beyond the scope of what this macro tries to do.
   the code below ensures that things don't break horribly if we run into
   one, but does not try too hard to get things pretty. #}
  <fieldset>
    <legend>{{field.label}}</legend>
    {%- for subfield in field %}
      {% if not bootstrap_is_hidden_field(subfield) -%}
        {{ form_field(subfield,
                      form_type=form_type,
                      horizontal_columns=horizontal_columns,
                      button_map=button_map) }}
      {%- endif %}
    {%- endfor %}
  </fieldset>
{% else -%}
  <div class="form-group {% if field.errors %} has-error{% endif -%}
                         {%- if field.flags.required %} required{% endif -%}
  ">
      {%- if form_type == "inline" %}
        {{field.label(class="sr-only")|safe}}
        {% if field.type == 'FileField' %}
          {{field(**kwargs)|safe}}
        {% else %}
          {{field(class="form-control", **kwargs)|safe}}
        {% endif %}
      {% elif form_type == "horizontal" %}
        {{field.label(class="control-label " + (
          " col-%s-%s" % horizontal_columns[0:2]
        ))|safe}}
        <div class=" col-{{horizontal_columns[0]}}-{{horizontal_columns[2]}}">
          {% if field.type == 'FileField' %}
            {{field(**kwargs)|safe}}
          {% else %}
            {{field(class="form-control", **kwargs)|safe}}
          {% endif %}
        </div>
        {%- if field.errors %}
          {%- for error in field.errors %}
            {% call _hz_form_wrap(horizontal_columns, form_type, required=required) %}
              <p class="help-block">{{error}}</p>
            {% endcall %}
          {%- endfor %}
        {%- elif field.description -%}
          {% call _hz_form_wrap(horizontal_columns, form_type, required=required) %}
            <p class="help-block">{{field.description|safe}}</p>
          {% endcall %}
        {%- endif %}
      {%- else -%}
        {{field.label(class="control-label")|safe}}
        {% if field.type == 'FileField' %}
          {{field(**kwargs)|safe}}
        {% else %}
          {{field(class="form-control", **kwargs)|safe}}
        {% endif %}

        {%- if field.errors %}
          {%- for error in field.errors %}
            <p class="help-block">{{error}}</p>
          {%- endfor %}
        {%- elif field.description -%}
          <p class="help-block">{{field.description|safe}}</p>
        {%- endif %}
      {%- endif %}
  </div>
{% endif %}
{% endmacro %}

{# valid form types are "basic", "inline" and "horizontal" #}
{% macro quick_form(form,
                    action="",
                    method="post",
                    extra_classes=None,
                    role="form",
                    form_type="basic",
                    horizontal_columns=('lg', 2, 10),
                    enctype=None,
                    button_map={},
                    id="",
                    novalidate=False) %}
{#-
action="" is what we want, from http://www.ietf.org/rfc/rfc2396.txt:

4.2. Same-document References

   A URI reference that does not contain a URI is a reference to the
   current document.  In other words, an empty URI reference within a
   document is interpreted as a reference to the start of that document,
   and a reference containing only a fragment identifier is a reference
   to the identified fragment of that document.  Traversal of such a
   reference should not result in an additional retrieval action.
   However, if the URI reference occurs in a context that is always
   intended to result in a new request, as in the case of HTML's FORM
   element, then an empty URI reference represents the base URI of the
   current document and should be replaced by that URI when transformed
   into a request.

 -#}
{#- if any file fields are inside the form and enctype is automatic, adjust
    if file fields are found. could really use the equalto test of jinja2
    here, but latter is not available until 2.8

    warning: the code below is guaranteed to make you cry =(
#}
{%- set _enctype = [] %}
{%- if enctype is none -%}
  {%- for field in form %}
    {%- if field.type == 'FileField' %}
      {#- for loops come with a fairly watertight scope, so this list-hack is
          used to be able to set values outside of it #}
      {%- set _ = _enctype.append('multipart/form-data') -%}
    {%- endif %}
  {%- endfor %}
{%- else %}
  {% set _ = _enctype.append(enctype) %}
{%- endif %}
<form
  {%- if action != None %} action="{{action}}"{% endif -%}
  {%- if id %} id="{{id}}"{% endif -%}
  {%- if method %} method="{{method}}"{% endif %}
  class="form
    {%- if extra_classes %} {{extra_classes}}{% endif -%}
    {%- if form_type == "horizontal" %} form-horizontal
    {%- elif form_type == "inline" %} form-inline
    {%- endif -%}
  "
  {%- if _enctype[0] %} enctype="{{_enctype[0]}}"{% endif -%}
  {%- if role %} role="{{role}}"{% endif -%}
  {%- if novalidate %} novalidate{% endif -%}
  >
  {{ form.hidden_tag() }}
  {{ form_errors(form, hiddens='only') }}

  {%- for field in form %}
    {% if not bootstrap_is_hidden_field(field) -%}
      {{ form_field(field,
                    form_type=form_type,
                    horizontal_columns=horizontal_columns,
                    button_map=button_map) }}
    {%- endif %}
  {%- endfor %}

</form>
{%- endmacro %}

app/templates/changes/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>{{ project.description }}</h1>
</div>
<div class="row">
    <div class="col-md-12">
    	<h3>Commits</h3>
    	<table class="table">
    		{% for commit in project.iter_commits() %}
    		<tr>
    			<td>{{ commit.committed_datetime.strftime('%Y-%m-%d %H:%M') }}</td>
    			<td>{{ commit.message }}</td>
    			<td>{{ commit.author.name }} ({{ commit.author.email }})</td>
    		</tr>
    		{% endfor %}
    	</table>
    </div>
</div>

{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/flatdebs/all.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>Projects</h1>
</div>
<div class="row">
    <div class="col-md-offset-1 col-md-10">
        {% for name, project in projects.items()|sort %}
            <div class="panel panel-default">
                <div class="panel-heading"><a href="{{ url_for('projects.get', repo_name=name) }}">{{ name }}</a></div>
                <div class="panel-body">{{ project.working_dir }}</div>
            </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/main/index.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}

<div class="page-header">
	<div class="row">
        <h1 class="col-lg-6">FlatDeb {{ flatdebs| length }} Applications</h1>
	<form class="navbar-form navbar-right search-btn-group">
		<div class="form-group">
			<input type="text" id=search-flatdeb-input class="form-control" placeholder="Search">
		</div>
	</form>
	</div>
</div>

<div class="container">
	<div class="row">
		{% for name, flatdeb in flatdebs.items()|sort %} 
		<div class = "col-sm-6 col-md-3 flatdeb-info">
            <a href="{{ url_for('main.get', pkgname=name) }}">
			<div class="thumbnail">
                <img class="flatdeb-thumbnail" src="/resources/icons/{{ name }}" alt="Generic placeholder thumbnail">
			</div>
            </a>

			<div class = "flatdeb-caption">
				<h3 class="flatdeb-name">{{ name.split('.')[-1] }}</h3>
				<p>{{ flatdeb.description }}</p>

				<p>
				<!-- Button trigger modal -->
				<button type="button" class="btn btn-primary btn-md" data-toggle="modal"
					data-target="#installModal" data-pkgname={{ url_for('main.install', pkgname=name) }}>
					command
				</button>
				<a href="{{ url_for('main.appstream', pkgname=name) }}"
					class = "btn btn-default" role = "button">
					install
				</a>
			</div>
		</div>
		{% endfor %}
	</div>
</div>

<div class="modal fade" id="installModal" role="dialog">
	<div class="modal-dialog">
		<!-- Modal content-->
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal">&times;</button>
				<h4 class="modal-title">Install</h4>
			</div>
			<div class="modal-body">
				<p>Loading...</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
			</div>
		</div>

	</div>
</div>

{% endblock %}

{% block scripts %}
{{ super() }}
<script>
	$(document).ready(function(){
		$("#search-flatdeb-input").on("keyup", function() {
			var value = $(this).val().toLowerCase();
			$(".flatdeb-info").filter(function() {
				$(this).toggle($(this).find('.flatdeb-name').text().toLowerCase().indexOf(value) > -1);
			});
		});
		$("#installModal").on('show.bs.modal', function (event){
			var button = $(event.relatedTarget);
			var recipient = button.data('pkgname');
			var modal = $(this);
			modal.find('.modal-body').html(recipient);
			modal.find('.modal-body').load(recipient);
		});
	});
</script>
{% endblock %}